name: Build and Deploy with Approval

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.upload-artifact.outputs.artifact-path }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application
        run: echo "Building application for ${{ github.event.inputs.environment }} environment..."

      - name: Create Build Artifact
        id: upload-artifact
        run: |
          mkdir -p build
          echo "Artifact for ${{ github.event.inputs.environment }}" > build/artifact.txt
          echo "::set-output name=artifact-path::build/artifact.txt"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/artifact.txt

  

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Deploy Application
        run: |
          echo "Deploying application to ${{ github.event.inputs.environment }} environment..."
          echo "Using artifact: ${{ needs.build.outputs.artifact-path }}"
