name: Build and Deploy with Approval

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to (e.g., dev, staging, prod)"
        required: true
        default: "dev"
      version:
        description: "The version of the application to deploy"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.upload-artifact.outputs.artifact-path }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application
        run: echo "Building application for ${{ github.event.inputs.environment }} environment..."

      - name: Create Build Artifact
        id: upload-artifact
        run: |
          mkdir -p build
          echo "Artifact for ${{ github.event.inputs.environment }}" > build/artifact.txt
          echo "::set-output name=artifact-path::build/artifact.txt"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/artifact.txt

  approval:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Wait for Approval
        run: echo "Please approve the deployment from the GitHub Actions UI."

      - name: Pause for Approval
        run: |
          echo "Pausing workflow for manual approval..."
          sleep 3600  # This pauses the workflow for up to an hour for manual intervention

  deploy:
    runs-on: ubuntu-latest
    needs: approval

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Deploy Application
        run: |
          echo "Deploying application to ${{ github.event.inputs.environment }} environment..."
          echo "Using artifact: ${{ needs.build.outputs.artifact-path }}"
